name: Python CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pytest
        run: pip install pytest

      - name: Run Person 1 tests
        run: pytest test_app.py

      - name: Run Person 2 tests
        run: pytest test_calculator.py

      - name: Run Person 1 application
        run: python app.py

      - name: Run Person 2 application
        run: python calculator.py
